name: Minecraft Mod Compiler

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kodlari Kopyala
      uses: actions/checkout@v4

    - name: Java 17 Kur
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: src.zip Dosyasini Ac ve Harf Hatasını Otomatik Düzelt
      run: |
        if [ -f src.zip ]; then
          unzip src.zip
          rm src.zip
        fi
        if [ -f src/main/java/com/esp/WorlRendererMixin.java ]; then
          sed -i 's/public class WorldRendererMixin/public class WorlRendererMixin/g' src/main/java/com/esp/WorlRendererMixin.java
        fi

    - name: Gradle 8.3 Sürümünü Hazır İndir ve Kur
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.3'

    - name: Modu Derle (Tam Güç RAM ile)
      env:
        _JAVA_OPTIONS: "-Xmx4g -Xms2g"
      run: gradle build --no-daemon

    - name: Calisan Mod Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: FluxEsp-Mod-Paketi
        path: build/libs/*.jar
