name: Minecraft Mod Compiler

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kodlari Kopyala
      uses: actions/checkout@v4

    - name: Java 17 Kur
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: src.zip Dosyasini Ac
      run: |
        if [ -f src.zip ]; then
          unzip src.zip
          rm src.zip
        fi

    - name: Gradle Sistemini Otomatik Kur
      run: gradle wrapper --gradle-version 8.1.1

    - name: Modu Derle
      run: ./gradlew build

    - name: Calisan Mod Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: FluxEsp-Mod-Paketi
        path: build/libs/*.jar

